// ============================================================================
// AUTO-GENERATED FILE.
// Generated by embed_shaders.py
// DO NOT EDIT.
// ============================================================================

#pragma once

#include <array>
#include <string_view>
#include <cassert>

namespace axle::fw::generated
{

struct EmbeddedShader
{
    std::string_view moduleName;
    std::string_view source;
};

inline constexpr std::string_view engine_transform = R"AXLE_SHADER(
module engine.transform

float4x4 GetModelTransform();
)AXLE_SHADER";

inline constexpr std::string_view engine_transform_gpu_driven = R"AXLE_SHADER(
StructuredBuffer<float4x4> g_InstanceMatrices;

float4x4 GetModelTransform()
{
    return g_InstanceMatrices[SV_InstanceID];
}
)AXLE_SHADER";

inline constexpr std::string_view engine_transform_instanced = R"AXLE_SHADER(
struct InstanceInput
{
    float4 row0 : INSTANCE_ROW0;
    float4 row1 : INSTANCE_ROW1;
    float4 row2 : INSTANCE_ROW2;
    float4 row3 : INSTANCE_ROW3;
};

static InstanceInput g_instance;

float4x4 GetModelTransform()
{
    return float4x4(
        g_instance.row0,
        g_instance.row1,
        g_instance.row2,
        g_instance.row3
    );
}
)AXLE_SHADER";

inline constexpr std::string_view engine_transform_uniform = R"AXLE_SHADER(
cbuffer PerObject : register(b1)
{
    float4x4 u_modelMatrix;
};

float4x4 GetModelTransform()
{
    return u_modelMatrix;
}
)AXLE_SHADER";

inline constexpr std::array<EmbeddedShader, 4> kShaders = {
    EmbeddedShader{ "engine/transform", engine_transform },
    EmbeddedShader{ "engine/transform_gpu_driven", engine_transform_gpu_driven },
    EmbeddedShader{ "engine/transform_instanced", engine_transform_instanced },
    EmbeddedShader{ "engine/transform_uniform", engine_transform_uniform },
};

constexpr const EmbeddedShader* Find(std::string_view moduleName)
{
    for (const auto& shader : kShaders)
    {
        if (shader.moduleName == moduleName)
            return &shader;
    }

    return nullptr;
}

constexpr const EmbeddedShader& GetRequired(std::string_view moduleName)
{
    auto* shader = Find(moduleName);
    assert(shader && "Embedded shader not found.");
    return *shader;
}

constexpr const auto& GetAll()
{
    return kShaders;
}

} // namespace axle::fw::generated
