#!/usr/bin/env python3

import argparse
import pathlib
import re


def make_identifier(path: pathlib.Path):
    ident = "_".join(path.with_suffix("").parts)
    ident = re.sub(r"[^a-zA-Z0-9_]", "_", ident)
    if ident and ident[0].isdigit():
        ident = "_" + ident
    return ident


def make_raw_delimiter(text: str):
    delim = "AXLE_SHADER"
    while f"){delim}\"" in text:
        delim += "_"
    return delim


def gather_shaders(root: pathlib.Path):
    shaders = []

    for file in sorted(root.rglob("*.slang")):
        rel = file.relative_to(root)

        shaders.append({
            "identifier": make_identifier(rel),
            "module": rel.with_suffix("").as_posix(),
            "source": file.read_text(encoding="utf-8")
        })

    return shaders


def generate(root: pathlib.Path, output: pathlib.Path):
    shaders = gather_shaders(root)

    with output.open("w", encoding="utf-8", newline="\n") as out:

        out.write("// ============================================================================\n")
        out.write("// AUTO-GENERATED FILE.\n")
        out.write("// Generated by embed_shaders.py\n")
        out.write("// DO NOT EDIT.\n")
        out.write("// ============================================================================\n\n")

        out.write("#pragma once\n\n")
        out.write("#include <array>\n")
        out.write("#include <string_view>\n")
        out.write("#include <cassert>\n\n")

        out.write("namespace axle::fw::generated\n{\n\n")

        out.write("struct EmbeddedShader\n")
        out.write("{\n")
        out.write("    std::string_view moduleName;\n")
        out.write("    std::string_view source;\n")
        out.write("};\n\n")

        #
        # Individual constexpr shader variables
        #
        for shader in shaders:

            delim = make_raw_delimiter(shader["source"])

            out.write(
                f"inline constexpr std::string_view {shader['identifier']} = "
                f'R"{delim}(\n'
            )

            out.write(shader["source"])

            if not shader["source"].endswith("\n"):
                out.write("\n")

            out.write(f"){delim}\";\n\n")

        #
        # Master array
        #
        out.write(
            f"inline constexpr std::array<EmbeddedShader, {len(shaders)}> kShaders = {{\n"
        )

        for shader in shaders:
            out.write(
                f'    EmbeddedShader{{ "{shader["module"]}", {shader["identifier"]} }},\n'
            )

        out.write("};\n\n")

        #
        # Find()
        #
        out.write(
            "constexpr const EmbeddedShader* Find(std::string_view moduleName)\n"
        )
        out.write("{\n")
        out.write("    for (const auto& shader : kShaders)\n")
        out.write("    {\n")
        out.write("        if (shader.moduleName == moduleName)\n")
        out.write("            return &shader;\n")
        out.write("    }\n\n")
        out.write("    return nullptr;\n")
        out.write("}\n\n")

        #
        # GetRequired()
        #
        out.write(
            "constexpr const EmbeddedShader& GetRequired(std::string_view moduleName)\n"
        )
        out.write("{\n")
        out.write("    auto* shader = Find(moduleName);\n")
        out.write("    assert(shader && \"Embedded shader not found.\");\n")
        out.write("    return *shader;\n")
        out.write("}\n\n")

        #
        # GetAll()
        #
        out.write(
            "constexpr const auto& GetAll()\n"
        )
        out.write("{\n")
        out.write("    return kShaders;\n")
        out.write("}\n\n")

        out.write("} // namespace axle::fw::generated\n")


def main():

    parser = argparse.ArgumentParser(
        description="Embed every .slang file into one generated C++ header."
    )

    parser.add_argument(
        "shader_directory",
        help="Directory to recursively scan"
    )

    parser.add_argument(
        "output_header",
        help="Output .hpp file"
    )

    args = parser.parse_args()

    root = pathlib.Path(args.shader_directory).resolve()

    if not root.exists():
        raise RuntimeError(f"{root} does not exist.")

    generate(root, pathlib.Path(args.output_header))


if __name__ == "__main__":
    main()